---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-thetagn-vol
  annotations:
    pv.beta.kubernetes.io/gid: "0"
  labels:
    zone: thetagn
  namespace: theta
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: vol_theta
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
